// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActAMh0_pmCmOAwVGYYVCz6qrxDnGcJbc',
    appId: '1:750703215477:web:7f5132c37012489ab3093c',
    messagingSenderId: '750703215477',
    projectId: 'aikidomaruyama-28bc6',
    authDomain: 'aikidomaruyama-28bc6.firebaseapp.com',
    storageBucket: 'aikidomaruyama-28bc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGiPoOjXBnLwtvbfF6HoA9qJB6sPRjSY',
    appId: '1:750703215477:android:dccbe8acc3ae14a7b3093c',
    messagingSenderId: '750703215477',
    projectId: 'aikidomaruyama-28bc6',
    storageBucket: 'aikidomaruyama-28bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFW5AsBTIBHzT1SK3D1zDKXxGTWJJvao',
    appId: '1:750703215477:ios:7291e81c85e2c868b3093c',
    messagingSenderId: '750703215477',
    projectId: 'aikidomaruyama-28bc6',
    storageBucket: 'aikidomaruyama-28bc6.firebasestorage.app',
    iosBundleId: 'br.com.maguinhoaju.aikidomaruyama',
  );
}
